name: batt
description: Flutter Build and Test Tool.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

dependencies:
  args: any
  file: ^7.0.0
  logging: any
  meta: any
  path: any
  platform: any
  process_runner: any

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
